name: Project one

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v4
      run: |
        echo "Build project one"
  
  test:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v4
      run: |
        echo "Test project one"